### ISSUE TITLE
Upgrade to 5.5 breaks compatibility with older Angular versions

### ISSUE THREAD

**Issue by DaanTul** [Agranom/ngx-material-timepicker#315]
Hello,

When updating to v5.5 to solve the .replace on null issue. We encounter an

`error TS1086: An accessor cannot be declared in an ambient context.` 

error when trying to run or test the project. After some googling I think the problem may be with getters and setters working differently between Angular 8(w Typescript 3.4.5) and Angular 9 with a higher version of Typescript.

**Comment by Agranom** [comment]
Maybe it's time to update your project to ng9 ?) Unfortunately I cannot support olred versions as well ((

**Comment by Agranom** [comment]
Rebuild the package with ng8. Update to v5.5.1 pls

**Comment by DaanTul** [comment]
Did it, seems to work fine in development, but build --prod gives errors with the angular optimizer using devkit 0.800.0. This seems to be an error with Angular CLI. Might be related to other issues
